# Generated by Django 4.2 on 2023-04-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
